### ISSUE TITLE
EELayer Tracker: Cleanup/Features

### ISSUE THREAD

**Issue by ibgreen** [UnfoldedInc/earthengine-layers#3]
## Fixes

- [x] CSS Layout of login button is really bad
- [x] Upgrade deck.gl to 8.1
- [x] Fix flicker of tile layer
- [ ] Test error messages under Node.js (presumably some deck.gl scaffolding copy pasta that must be removed).

## Features

- [x] Build script version of earth-engine-layers and publish **anonymously**. (Maybe from build folder one of our public repos, such as pydeck or unfolded.gl.)
- [x] Check that layer module loads in pydeck.
- [x] Make EELayer work with serialized EE objects. 
- [x] Test EELayer in pydeck with eeObject.serialize()
- [x] Update ee-demo example so that it authenticates using python EE credentials.
- [x] Implement `defaultProps`

## Basics

- [x] Fix ee-demo example so that it authenticates using Google login.
- [x] Copy ee-layer, ee-demo, google login code and make it pass lint and test
- [x] Scaffold repo with standard monorepo setup.
