### ISSUE TITLE
Website improvements tracker

### ISSUE THREAD

**Issue by kylebarron** [UnfoldedInc/earthengine-layers#69]
Some of these will need to be done in the [ocular-theme](https://github.com/uber-web/ocular/blob/master/modules/gatsby-theme-ocular/README.md) directly.

- [ ] Fix mobile layout (**Ocular**). Currently subpar:
	<img height="400px" src="https://user-images.githubusercontent.com/15164633/82944887-3ea30c00-9f59-11ea-89f3-9e8908a59d78.png" />

- [ ] Loading spinner for examples. Would be helpful to have a `Deck`-level `isLoading` prop

- [ ] Support GIFs as image thumbnails on the Examples gallery page (Ocular change) and use a GIF for the ImageCollection animation thumbnail.

- [ ] Add note to ImageCollection example that it won’t show up on Safari/iOS devices

- [ ] Add image/GIF behind “earthengine-layers” on homepage, so that it's visible without a login needed.

- [ ] change pointerEvents on infobox to allow selection. Currently you can click links but can't select text.

- [ ] Example subtitles should be more left-aligned:

	<img height="300px" src="https://user-images.githubusercontent.com/15164633/82945618-752d5680-9f5a-11ea-8794-b3a411c48851.png" />

- [ ] Blue labels on published site (only shows for me in Incognito mode):

	<img height="300px" src="https://user-images.githubusercontent.com/15164633/82945181-b96c2700-9f59-11ea-87a2-863e08e5f2c8.png" />

	Also shows up in loaders.gl, so I think this is an Ocular fix:

	<img height="300px" src="https://user-images.githubusercontent.com/15164633/82945211-c852d980-9f59-11ea-84b4-20295a6725a2.png" />
